### ISSUE TITLE
Can we extend Sparse4D to a new dataset?

### ISSUE THREAD

**Issue by BaoWentz** [linxuewu/Sparse4D#14]
https://github.com/linxuewu/Sparse4D/blob/c48ecd2b020d7770faaa865f577eed28406b75e9/projects/mmdet3d_plugin/models/blocks.py#L514
Assuming that we are using a new trainset composed by different cars and they have different projection_mats(lidar2img) to train a model, now we are trying to use this model in a new car without lidar. The question is whitch projection_mat should we choose?Thanks a lot!

**Comment by linxuewu** [comment]
Any coordinate system that is fixed relative to the ego vehicle is fine, and the commonly used one is the "vehicle coordinate system".

**Comment by BaoWentz** [comment]
As far as I know the camera coordinate system and lidar coordinate system are not fixed relative to the ego vehicle for all nuscenes data. So will we futher improve the mAP by changing lidar coordinate system into CAM_FRONT coordinate system?Thanks!

**Comment by linxuewu** [comment]
The camera coordinate system and lidar coordinate system are fixed relative to the ego vehicle. The reason why ego2cam and ego2lidar are changing is to synchronize the time of multiple sensors.mAP does not vary with coordinate system changes.
